/*
* https://developer.limneos.net/?ios=17.1&framework=CoreTelephony.framework&header=CTStewieFindMyMessage.h
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CTStewieMessageOutgoing.h>

@class NSData, NSString;

@interface CTStewieFindMyMessage : NSObject <CTStewieMessageOutgoing> {

	NSData* _encryptedData;
}
@property (nonatomic,retain) NSData * encryptedData;                //@synthesize encryptedData=_encryptedData - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)supportsSecureCoding;
-(id)initWithData:(id)arg1 error:(id*)arg2 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSData *)encryptedData;
-(BOOL)isEqualToFindMyMessage:(id)arg1 ;
-(void)setEncryptedData:(NSData *)arg1 ;
@end